id = "base16"
name = "base16"
version = "0.1.1"
schema_version = 1
authors = [
    "Brooks Swinnerton <bswinnerton@gmail.com>",
    "Tim Chmielecki <me@timcki.com>",
    "Kevin Gyori <hi@gyori.me>",
]
description = "Chris Kempson's base16 Themes"
repository = "https://github.com/bswinnerton/base16-zed"
